package bradleyross.common;
//
//  MySQL1.java
//  MySQL1
//
//  Created by Bradley Ross on Mon Apr 07 2003.
//  Copyright (c) 2003 __MyCompanyName__. All rights reserved.
//
//	For information on setting Java configuration information, including 
//	setting Java properties, refer to the documentation at
//		http://developer.apple.com/techpubs/java/java.html
//

import java.sql.ResultSetMetaData;
import java.sql.SQLException;
/**
* Provide a set of
* classes to help with the processing of
* SQL statements.
*
*
* @author Bradley Ross
*/
public class sqlHelper
   {
   /**
   * Determines amount of intermediate diagnostic messages to
   * be printed.
   * <p>See the description for the setDebugLevel method
   *    for more information.</p>
   */
   protected int debugLevel = 0;
   /**
   * Set amount of diagnostic messages to be printed.
   * 
   * A value of 0 indicates that no diagnostic messages are
   * to be printed.  Increased
   * values increase the quantity of diagnostic messages.
   * @param level Desired level of diagnostic messages.
   */
   public void setDebugLevel (int level)
      { debugLevel = level; }
   /**
   * Print ResultSet generated by SQL query.
   *<p>This version has the destination for the 
   *   listing set to System.out</p>
   * @param rs ResultSet to be printed
   * @see System
   */
   public void printResultSet(java.sql.ResultSet rs)
      {
      printResultSet(rs, System.out);
      }
   /**
   * Print ResultSet generated by SQL query.
   * <p>This version uses a java.io.OutputStream
   *    so that the results can be sent to a file
   *    or some other container.</p>
   * <p>A <code>java.io.OutputSteam</code> object can be
   *    created using the Java statement
   *    <code>java.io.FileOutputStream outputFile =
   *    new java.io.FileOutputStream(outputFileName);
   *    </code> where <code>outputFileName</code>
   *    is a <code>String</code> object containing the
   *    name of the output file to be created.</p>
   * @param rs ResultSet object to be displayed
   * @param output Destination for listing
   * @see java.io.FileOutputStream
   */
   public void printResultSet(java.sql.ResultSet rs,
          java.io.OutputStream output)
      {
      try
         {
         java.io.PrintStream out =
            new java.io.PrintStream(output);
         printResultSet(rs, out);
         out.flush();
         }
      catch (Exception e)
         {
         System.out.println(e.getMessage());
         }
      }
   /**
   * Print ResultSet generated by SQL query.
   * <p>The object System.out is a java.io.PrintStream
   *    object.  This version of the method is therefore
   *    suitable for printing to System.out.</p>
   * @param rs ResultSet to be printed
   * @param output Destination for listing
   * @see System
   */
   public void printResultSet(java.sql.ResultSet rs, 
          java.io.PrintStream output) 
      {
      try
         {
         if (debugLevel > 0)
            { output.println("Starting printResultSet"); }
          //
          ResultSetMetaData meta = rs.getMetaData();
          output.print(meta.getColumnCount());
          output.println(" columns");
          for (int i=1; i <= meta.getColumnCount(); i++)
             {
             output.print(meta.getColumnLabel(i));
             output.print("   ");
             output.print(meta.getColumnTypeName(i));
             output.println("   ");
             }
          output.println("***");
          while (rs.next())
             {
             output.println("*** New record");
             for (int i=1; i <= meta.getColumnCount(); i++)
                { output.println(rs.getString(i)); }
             }
          }
       catch (SQLException ex1)
          {
          output.println("SQLException");
          ex1.printStackTrace(output);
          }
       catch (Exception ex)
          {
          output.println("Unknown Exception");
          ex.printStackTrace(output);
          }
   }
}
